// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $ContactForm from "./islands/ContactForm.tsx";
import * as $FadeIn from "./islands/FadeIn.tsx";
import * as $ProjectGallery from "./islands/ProjectGallery.tsx";
import * as $ProjectModal from "./islands/ProjectModal.tsx";
import * as $Projects from "./islands/Projects.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ContactForm.tsx": $ContactForm,
    "./islands/FadeIn.tsx": $FadeIn,
    "./islands/ProjectGallery.tsx": $ProjectGallery,
    "./islands/ProjectModal.tsx": $ProjectModal,
    "./islands/Projects.tsx": $Projects,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
